# Generated by Django 4.2.7 on 2025-04-20 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial_bankroll', models.FloatField(default=100.0)),
                ('num_rounds', models.IntegerField(default=100)),
                ('bet_fraction', models.FloatField(default=0.1)),
                ('num_simulations', models.IntegerField(default=1000)),
                ('strategy', models.CharField(choices=[('fixed_fraction', 'Fixed Fraction'), ('kelly_criterion', 'Kelly Criterion'), ('martingale', 'Martingale'), ('custom', 'Custom Strategy')], default='fixed_fraction', max_length=50)),
                ('is_parameter_sweep', models.BooleanField(default=False)),
                ('sweep_parameter', models.CharField(blank=True, max_length=50)),
                ('sweep_start', models.FloatField(blank=True, null=True)),
                ('sweep_end', models.FloatField(blank=True, null=True)),
                ('sweep_steps', models.IntegerField(blank=True, null=True)),
                ('custom_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='strategies.strategy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('mean_final_bankroll', models.FloatField()),
                ('median_final_bankroll', models.FloatField()),
                ('std_final_bankroll', models.FloatField()),
                ('min_final_bankroll', models.FloatField()),
                ('max_final_bankroll', models.FloatField()),
                ('probability_of_ruin', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('detailed_results', models.TextField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='simulation.simulation')),
            ],
        ),
    ]
